pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://neoforged.forgecdn.net/releases/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
    }
}

rootProject.name = 'MTR-ANTE-26.2'
include 'common', 'fabric', 'neoforge'
