name: Build

on:
  push:
    branches: [master, '1.21.1']
    tags: ['1.1.1-1.21.1-*']
  pull_request:
    branches: [master, '1.21.1']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ANTE
        uses: actions/checkout@v5
        with:
          path: mtr-ante
      - name: Checkout pinned MTR 3.3.4
        uses: actions/checkout@v5
        with:
          repository: linlunaire/Minecraft-Transit-Railway
          ref: 99fa5a35fef8e9aa2b7659cdca9cfc70841d037c
          path: Minecraft-Transit-Railway-1.21.1
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: graalvm
          java-version: '21'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build MTR dependency
        working-directory: Minecraft-Transit-Railway-1.21.1
        run: chmod +x gradlew && ./gradlew build --stacktrace
      - name: Build ANTE Fabric and NeoForge
        working-directory: mtr-ante
        run: chmod +x gradlew && ./gradlew build --stacktrace
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ANTE-1.21.1
          path: mtr-ante/build/release/MTR-ANTE-*-1.21.1-*.jar
          if-no-files-found: error
